name: tofu-fmt
description: Rewrite OpenTofu files into canonical format
author: Daniel Flook

inputs:
  path:
    description: The path containing OpenTofu files to format.
    required: false
    default: "."
  workspace:
    description: |
      OpenTofu workspace to inspect when discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: "default"
  backend_config:
    description: |
      List of OpenTofu backend config values, one per line. This is used for discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of OpenTofu backend config files to use, one per line. This is used for discovering the OpenTofu version to use, if the version is not otherwise specified.
      See [dflook/tofu-version](https://github.com/dflook/terraform-github-actions/tree/main/tofu-version#tofu-version-action) for details.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:3b17c6aec3cf2a1f21e7ca7c7b44c50193c735c285a3d18d82d59e3f1000d3cb
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
